### PR TITLE
Feat: Added landing page

### PR DESCRIPTION
**Pull request by Prabhav-Sharma**

### CODE REVIEW

**Comment by ashishnnnnn** [comment]
It looks good.. Prabhav..

**Review by AmishMishra11 — COMMENTED** [review]
Looks good.

**Comment by prathmeshjagtap** [comment]
Looks good and the code is also neat and clean

**Comment by tanishk15sharma** [comment]
cake work !

**Comment by way2nizam** [comment]
looks very nice

**Pull request merged**
